# generated by zon2nix (https://github.com/nix-community/zon2nix)
{
  linkFarm,
  fetchzip,
}:
linkFarm "zig-packages" [
  {
    name = "122059777e9e24227733f386b2929a78e15be9b748c99dba0d209744c910671b101c";
    path = fetchzip {
      url = "https://pkg.machengine.org/brotli/4c10522a5fa3b4fd7f8beedc8af1e20309719da9.tar.gz";
      hash = "sha256-37XYOEkszZ2xeeDUG8i+8THzLVnIINnPL97bn44C854=";
    };
  }
  {
    name = "122062d301a203d003547b414237229b09a7980095061697349f8bef41be9c30266b";
    path = fetchzip {
      url = "https://github.com/Hejsil/zig-clap/archive/refs/tags/0.9.1.tar.gz";
      hash = "sha256-pscDsE1jJK1Nktq7rv/ScvsDqvvklFvtiGqOFf2eWvY=";
    };
  }
  {
    name = "1220687c8c47a48ba285d26a05600f8700d37fc637e223ced3aa8324f3650bf52242";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-wayland/archive/v0.2.0.tar.gz";
      hash = "sha256-dvit+yvc0MnipqWjxJdfIsA6fJaJZOaIpx4w4woCxbE=";
    };
  }
  {
    name = "1220babb7939707ca390b934657dfd3c8c3a6a78cc9442e4cbd43e3f9ffd49daec9e";
    path = fetchzip {
      url = "https://github.com/hexops/freetype/archive/refs/heads/master.tar.gz";
      hash = "sha256-7WelJ62c/28QlxTwsooVsAbYmhp3FmxKNq1Tte2JcMY=";
    };
  }
]
